[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_CONVEX_URL = "https://aki-sato-compass.convex.cloud"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200